/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PayRouteImport } from './routes/pay'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSectionRouteImport } from './routes/admin/$section'
import { Route as AdminSearchRouteImport } from './routes/admin/search'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTelegramBotRouteImport } from './routes/api/telegram.$bot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramBotRoute = ApiTelegramBotRouteImport.update({
  id: '/api/telegram/$bot',
  path: '/api/telegram/$bot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courier': typeof CourierRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/shop': typeof ShopRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/search': typeof AdminSearchRoute
  '/api/events': typeof ApiEventsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/telegram/$bot': typeof ApiTelegramBotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courier': typeof CourierRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/shop': typeof ShopRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/search': typeof AdminSearchRoute
  '/api/events': typeof ApiEventsRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/telegram/$bot': typeof ApiTelegramBotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courier': typeof CourierRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/shop': typeof ShopRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/search': typeof AdminSearchRoute
  '/api/events': typeof ApiEventsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/telegram/$bot': typeof ApiTelegramBotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/courier'
    | '/login'
    | '/pay'
    | '/shop'
    | '/admin/$section'
    | '/admin/search'
    | '/api/events'
    | '/admin/'
    | '/api/auth/$'
    | '/api/telegram/$bot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courier'
    | '/login'
    | '/pay'
    | '/shop'
    | '/admin/$section'
    | '/admin/search'
    | '/api/events'
    | '/admin'
    | '/api/auth/$'
    | '/api/telegram/$bot'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/courier'
    | '/login'
    | '/pay'
    | '/shop'
    | '/admin/$section'
    | '/admin/search'
    | '/api/events'
    | '/admin/'
    | '/api/auth/$'
    | '/api/telegram/$bot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CourierRoute: typeof CourierRoute
  LoginRoute: typeof LoginRoute
  PayRoute: typeof PayRoute
  ShopRoute: typeof ShopRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTelegramBotRoute: typeof ApiTelegramBotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/$bot': {
      id: '/api/telegram/$bot'
      path: '/api/telegram/$bot'
      fullPath: '/api/telegram/$bot'
      preLoaderRoute: typeof ApiTelegramBotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CourierRoute: CourierRoute,
  LoginRoute: LoginRoute,
  PayRoute: PayRoute,
  ShopRoute: ShopRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTelegramBotRoute: ApiTelegramBotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
